---
title: "p8105_HW5_rat2134"
author: "Robert Tumasian"
date: "11/3/2019"
output: github_document
---

```{r, message = FALSE}
#Load required packages
library(tidyverse)
```

# Homework 5
## Problem 1
```{r}
#Loading data
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
#Function
problem_1_function = function(x) {
  
  if (is.numeric(x)) {
    ifelse(is.na(x), mean(x, na.rm = TRUE), x)
  } else if (is.character(x)){
    ifelse(is.na(x), "virginica", x)
  }

}
```

```{r}
#Applying function to each column of 'iris_with_missing' using 'map'
iris_without_missing = map(iris_with_missing, problem_1_function)
```

## Problem 2
```{r, message = FALSE}
#Load data
longitudinal_data = map_df(.x = list.files("./hw5_data"), 
                            ~ read_csv(str_c("./hw5_data\\", .x)))
longitudinal_data
```

```{r}
#Tidy data
longitudinal_data_tidy = 
  longitudinal_data %>%
    mutate(id = 1:20,
           arm = c(rep("control", 10), rep("experimental", 10))) %>%
    pivot_longer(week_1:week_8, 
                 names_to = "week", 
                 values_to = "observation") %>%
    mutate(week = str_replace(string = week,
                              pattern = ".*_",
                              replacement = ""))
```

```{r}
#Spaghetti plot
longitudinal_data_tidy %>%
  ggplot(aes(x = week, y = observation, group = id, color = arm)) +
  geom_line() +
  labs(
    title = "Observations for each subject over time, by arm",
    x = "Week",
    y = "Observation",
    color = "Arm"
  )
```

Overall, we can see that subjects in the experimental arm have higher observation values over time compared to subjects in the control arm. At 8 weeks, all subjects in the control group have lower observation values than those in the experimental group.

## Problem 3
```{r}
#Set design elements
n = 30

```




